### ISSUE TITLE
Failed to save as video

### ISSUE THREAD

**Issue by Inferencer** [numz/wav2lip_uhq#1]
Got this error after generating all my images, seems it couldnt save as a video file

my inference was
`python wav2lip_uhq.py -f C:/Users/leolo/Documents/bad2.mp4 -i C:/Users/leolo/Documents/test.mp4`

Error:
```
[INFO] Create Video output!
Traceback (most recent call last):
  File "C:\Users\leolo\wav2lip_uhq\wav2lip_uhq.py", line 183, in <module>
    main()
  File "C:\Users\leolo\wav2lip_uhq\wav2lip_uhq.py", line 170, in main
    create_video_from_images(args, frame_number-1)
  File "C:\Users\leolo\wav2lip_uhq\wav2lip_uhq.py", line 30, in create_video_from_images
    subprocess.run(
  File "C:\Users\leolo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\leolo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\leolo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1378, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\leolo\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 561, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\leolo\AppData\Local\Programs\Python\Python310\lib\os.py", line 822, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not int
```

**Comment by numz** [comment]
Thank you for your report, I indeed made a mistake on line 30, it should be str(nb_frames), it should be corrected now
