### ISSUE TITLE
After the installation, the web UI cannot be accessed.

### ISSUE THREAD

**Issue by chaorenai** [numz/wav2lip_uhq#5]
<img width="699" alt="微信图片_20231217164558" src="https://github.com/numz/wav2lip_uhq/assets/121802291/adc9949b-86ce-415f-9fb2-0fc8243f781a">
venv "D:\software\webui\venv\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: v1.6.1
Commit hash: 4afaaf8a020c1df457bcf7250cb1c7f609699fa7
Traceback (most recent call last):
  File "D:\software\webui\launch.py", line 50, in <module>
    main()
  File "D:\software\webui\launch.py", line 41, in main
    prepare_environment()
  File "D:\software\webui\modules\launch_utils.py", line 356, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
请按任意键继续. . .

**Comment by stasilino** [comment]
Problem with this extension on any STABLE DIFFUSION builds
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.1-latest
Commit hash: f11456e2d38d6b7f8432cd6952fb2f10fc2081b3
Traceback (most recent call last):
  File "D:\AI\Matrix\Data\Packages\Stable Diffusion WebUI Forge\launch.py", line 48, in <module>
    main()
  File "D:\AI\Matrix\Data\Packages\Stable Diffusion WebUI Forge\launch.py", line 39, in main
    prepare_environment()
  File "D:\AI\Matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\launch_utils.py", line 429, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
